### ISSUE TITLE
How to set the configuration options?

### ISSUE THREAD

**Issue by kayman-mk** [AkiJoey/semantic-release-maven#16]
Hi,

what a nice plugin, good job!

But I have no idea how to set the configuration options. Could you please add an example to the `README.md`? I'd like to set the `profiles` option, but how? I am using the YAML format.

```yaml
branches:
  - main
  - release-dry-run

tagFormat: "${version}"

preset: 'conventionalcommits'

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - "@semantic-release/git"
  - "@semantic-release/github"
  - "@semantic-release/exec"
  - "semantic-release-maven"
```

**Comment by kayman-mk** [comment]
Solved:

```yaml
publish:
  - path: "semantic-release-maven"
    profiles:
      - release
```
